[package]
name = "ibisibi"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argh = "0.1.5"
serialport = "4.0.1"
thiserror = "1.0.26"

[target.arm-unknown-linux-gnueabihf]
linker = "/home/krachzack/Development/rpi-newer-crosstools/x64-gcc-6.3.1/arm-rpi-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc"
